### ISSUE TITLE
LUMEN data transformation workflow

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-product-design#138]
An issue to capture the work on data transformation workflow in DASH.

first mockup:
https://drive.google.com/file/d/0B4C2-GDdmwzKNnY4dWF6RjBvRlE/view?usp=sharing

**Comment by mtwestra** [comment]
comments:

 1) page 2: on the left hand side, as the first column, I'd show the record number (1,2,3,4,...)
 
 2) page 2: 'three data types' doesn't make much sense. I would show the data type above each column, right under the column heading

 3) page 7: 'hide column' doesn't need to be in the log I think - it is just a way to 'view' the data, it doesn't change the underlying data. 'delete column' would do that

 4) page 8:  I probably would't put a 'free form transform editor field', as it is very unclear for users what they should be doing there. I think for now, the transformations will always happen through interactions with the data grid. Perhaps we could add it later, but I think this will be hard to get right.

 5) Last page, we need to think a bit further about the structure of the options, especially given the facet / filter discussion. 
 I think the 'unique values' item needs to be on the same level as the 'filter' item, as you show on page 2.

**Comment by mtwestra** [comment]
Second mockup: https://drive.google.com/file/d/0B4C2-GDdmwzKNnRyVE5RbWwtVDg/view?usp=sharing

**Comment by mtwestra** [comment]
User stories DASH: https://docs.google.com/document/d/1HTF599eRrn0uMHxsd29XRkPgq2iwbquWx6FDIy8vclY/edit

Data transformations:
https://docs.google.com/document/d/1gJ7ebKR9wUod03491thJqvlcjk-v-c-z8duIh_5YNek/edit

**Comment by mtwestra** [comment]
#### Use case 1)
Take a data set with two columns: 'gender', and 'name'. The gender column only contains 'male' or 'female'. Say I want to transform all the female names to upper case. In that case, I would do this:

1) filter the data set on 'gender = female'
2) on the remaining data set, select the 'name' column, and select 'to uppercase'
3) remove filter.

In this case, I would expect the log to contain something like this (loosely based on openRefine):

{
  "transformation": "core/toUppercase"
  "description": "To Uppercase text transform on cells in column name",
  "context": {
    "filter": [
      {
        "query": "female",
        "columnName": "gender",
        "caseSensitive": false,
        "type": "text",
        "mode": "text"
      }
    ],
    "mode": "row-based"
  },
  "columnName": "name",
  "expression": "value.toUppercase()",
  "onError": "keep-original",
}

In this case, the filter acts as a context of the transformation. It is captured in the log, because without it, there would not be a way to concisely record the transformation - we would need to specify each changed row.

#### Use case 2
Take a data set with 4 columns: region, pump type, and functionality. Say I want a graph on the functionality of pump type 'Afridev', in region 'Opper Volta'. In that case, I would want to apply two filters on those columns to select the appropriate rows. I would first of all apply the filters, so I get the desired result on my screen. After that, I would want to 'apply the filters permenantly', so they become part of the transformation. When I do that, I would expect to see this in the log:

  "transformation": "core/select"
  "description": "Apply filter to select rows",
  "context": {
    "filter": [
      {
        "query": "Afridev",
        "columnName": "pump type",
        "caseSensitive": false,
        "type": "text",
        "mode": "text"
      },
      {
        "query": "Opper Volta",
        "columnName": "region",
        "caseSensitive": false,
        "type": "text",
        "mode": "text"
      }
    ],
    "mode": "row-based"
  },
}

In this case, the filter acts as a context to a 'select' transformation.

**Comment by mtwestra** [comment]
Take a data set with 4 columns: region, pump type, and functionality. Say I 
want a graph on the functionality of pump type 'Afridev', in region 'Opper Volta'. 
In that case, my first guess would be that I can create a filter on both columns
selecting the values I want. After I've done that, my screen shows me the filtered
dataset, which contains exactly the rows I want. When I click 'save', I would expect
that my dataset is now ok for visualisation.

However, this is not the case, the dataset still contains all the rows. So how do we 
make this clear to the user? How to guide the user to perform a special 'extract / select 
rows' action, when the datagrid already shows the 'right' data?

**Comment by mtwestra** [comment]
Latest mockups: https://drive.google.com/file/d/0B4C2-GDdmwzKSUI0dDRGejFtRzA/view?usp=sharing

**Comment by mtwestra** [comment]
page 3: I like the column editor! I guess when a checkbox is clicked, this means it is visible? Or is it the other way around? Perhaps we can clarify the meaning of the checkbox.

page 8: Perhaps we can show how many items are shown when the filter is active, so something like "150 (out of 10.000)"

page 9: the summarize shows the unique values, but this is not the intended meaning. The summary would divide the data set in groups based on the summary column, and then apply an operation on the other columns, such as unique, count, sum, average, etc. This is quite a difficult thing, and perhaps we can leave it out for now.

So then we could have: Filter, Sort, Unique values, Edit column, Edit cell, and Hide as items in the menu.

We still need a solution for the 'select' thing.

**Comment by mtwestra** [comment]
Mockup: https://drive.google.com/file/d/0B4C2-GDdmwzKNGpMN1FkNEx5cm8/view

**Comment by mtwestra** [comment]
mockup: https://drive.google.com/file/d/0B4C2-GDdmwzKejc5UTBhR2JlZTA/view?usp=sharing

**Comment by mtwestra** [comment]
@kiarii, some comments:
1) this layout mainly shows the simple operations on columns. Where would you specify more complex operations?
2) here, the transform log is quite hidden. I wonder if it is not better to put it forward more, so it becomes more of a thing that people add things to, remove things from. If it is more visible, the more complex operations can be done directly there.
3) there will need to be a way to delete and edit transforms.
4) In a sense, I think it is the conceptual difference between a transform log as just a 'history', and the transform chain as a concept that defines a transform process.

**Comment by Kiarii** [comment]
I have chosen not to make the transformation log a prominent feature on the transform screen since if is not the primary action that user should work with: the primary task being to view data, secondary: to make data transformations; working with the transformation log feels tertiary especially if we are homing in on excel users. 

As a prominent/central feature, the transform log leaves us with the same challenge of simplifying the conceptual model - what we had with the bulk column edits. A column specific action if applied from a 'column edit' menu might 'seem' as a separate thing from an action added on a transform log. 

With complex actions (merge, split, derive) the thinking is to provide a preview so the user knows what they are doing, and can 'Discard' an action after they have already committed it. We would need to expand a bit on Undo and Redo (user stories) to cover the extent here. 

we might be moving towards sth like this:
![extension](https://cloud.githubusercontent.com/assets/12692444/13947828/54d6871e-f025-11e5-9e39-b894a860ccec.png)

It feels like we have 3 main transform levels: Dataset editing, Column editing, Row editing.
From this illustration, Column and Dataset Editor (+ cell edit) actions would all be captured by the transform log, irrespective of where they are performed and thus without appearing to centralize actions to the transformation log

Lastly but not least is the feeling that the datagraft pipeline gives: a logical, structured and ordered data transformation; this would work quite well with 'pro' users (programmers, data scientists) - doing data transformations directly on the log itself. For less savvy users, separating transform actions from the log simplifies the interface, optimizing it specifically for the Action at hand and hiding all other complexity

**Comment by mtwestra** [comment]
@kiarii, yes, I see what you mean. Ok, let's go with this idea of having the transform log as you describe.

I am not sure I understand your split in 'Dataset editing, Column editing, Row editing'? For me, I see:

* Transformations that change the metadata of columns: move, rename, delete (for which you have a 'column editor')
* Transformations that act on a single column: filter, sort, whitespace, change type (what you show in the column header menu)
* Transformations that act on a single column, through a special view: unique values, cluster and edit (could be added to the column header menu I think)
* Transformations that act upon multiple columns: Split into multiple columns, Combine columns, Add derived column, Geocode, Join (need to have a special menu)
* Transformations that act on rows in multiple columns: Select/remove rows, Deduplicate rows, Group and aggregate (need to have a special menu)

**Comment by Kiarii** [comment]
@mtwestra I agree with these description of transformations, I had simplified the analogy for the sake of design thinking - in the sense that a data transformation involves a manipulation to a cell, a row, a column (or a number of these respectively) or to the dataset as a whole - in order to determine how best to group and present the respective transform actions on the interface

**Comment by mtwestra** [comment]
@kiarii, ok, clear.

New mockup: https://drive.google.com/file/d/0B4C2-GDdmwzKZEJYcThkQzJRbW8/view

Comments:
1) looks really good, I also like the build-in help options
2) a question: in the transform log window, we'll need a way to edit or delete items. Is that behind the ... icon?
3) I would probably rename the 'bulk row editor' to something more descriptive such as 'take/keep rows', or something that expresses the idea of 'selecting' rows.
4) Any idea already where to place the 'unique values' and 'cluster and edit' stuff?

**Comment by Kiarii** [comment]
@mtwestra replying to comments:

1. we are making some progress
2. Transform log items editing is possible through the 'more actions' icon - Do we need to delve into that for the MVP or do we postpone it for later?
3.  'Bulk row editor' I used as an umbrella where in addition to making bulk selections, bulk deletions, Deduplicate (which is also a bulk editing) would also come here. There was also the idea of unifying the terminology so that Bulk [row/colum] editor imply editing a number of [rows/columns]
4. 'Unique values' and 'Cluster and edit' could go to the column edit menu and and under a [more actions] menu along each column name (in the Bulk column editor) if need be

**Comment by mtwestra** [comment]
@kiarii,

on 2) for the MVP, we'll need the log editing I think, yes. Or at least a 'delete' icon there, so a transform can be undone. That might be enough for now
on 3) and 4) sounds good

**Comment by Kiarii** [comment]
https://drive.google.com/file/d/0B4C2-GDdmwzKUHVyeVd3TmN2M1U/view?usp=sharing
