### ISSUE TITLE
Lumen Flow import

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-product-design#140]
The issue is to design a user-friendly way of getting FLOW data into Lumen, which includes support for monitoring and repeated question groups

First mockup:
https://drive.google.com/file/d/0B4C2-GDdmwzKNkxveWUybHpxUlU/view

User stories:
https://docs.google.com/document/d/1DwHdSBQdvqhyb-NZcSA6tTJD39bj1hrjXbhLIoW5Y9Q/edit

**Comment by mtwestra** [comment]
@kiarii, comments:
1) the flow import will also need to specify the FLOW instance
2) the last item in the list 'update datasets created from AkvoFLOW survey data' is not clear to me. Do you mean the periodical update? And I don't think you can 'view akvoFLOW survey data' without importing it first. So perhaps the list should be:
* import AkvoFLOW survey data (this creates a copy of the data in DASH)
* periodically update datasets created from AkvoFLOW surveys (depending on the setting for this dataset)
3) on the question selection: it should be easy to select all questions. I wonder if this is actually necessary, as it will be quite easy to remove columns once the data is in DASH.
4) last page: it is not custom to display a (secret) API key - this should be hidden as much as possible. It should at least require the user to press a 'show API key' button or so.

**Comment by Kiarii** [comment]
Will update mockups respectively once we have a discussion with @iperdomo on which direction the auth should take for the mvp at least..

**Comment by iperdomo** [comment]
@Kiarii @mtwestra my comments

Page 2. There shouldn't be a dialog asking for FLOW's user/password, we know already if the user has access to some FLOW instance based on the current session and authorization token. Asking for a username/password for other system feels "fragile" from a security point of view. If we don't detect any access to a FLOW instance, we prompt for _key_, _secret_ and _instance. More details on Page 9.

Page 3. There is no notion of _OAuth2_ grants/scopes to FLOW, as a FLOW user we'll only _read_ data and never modify anything in FLOW. I think this step is not necessary.

Page 4. A FLOW user can have access to many instances, he/she needs to be able to pick the instance from a dropdown.

Page 4. The Survey list shouldn't be a dropdown. FLOW users are used to select surveys or forms in a folder structure. Having the survey list as a dropdown could lead to show into _repeated_ survey names (from different folders) and the user will not know which one is the one he wants. IMHO this should be a List (potentially exposing the folder structure).

Page 4. It's true that Dash should know about FLOW, but giving too much flexibility to the user (in terms of selecting which question to import) adds more complexity. IMHO _Hiding_/_Unhiding_ columns from the imported dataset should be a _transformation_ and not part of the import process.
I think we wanted to _streamline_ the import step with fewer steps, - e.g. When importing a CSV we don't have a preview to convert the column data-types, that's now a transformation - My feeling is that we're adding too many steps/options to the user. She/he should select the Survey or Form to import and that's all. Any data manipulation should be a transformation.

Page 9. When we don't detect access to FLOW instances we can prompt a dialog to use an API key, but there are 3 different textboxes, not only one: 
  * Instance URL - e.g. https://pilot.akvoflow.org
  * API Key - e.g. 1234
  * API Secret - e.g. bXlzdXBlcnNlY3JldA==

**Comment by Kiarii** [comment]
@iperdomo following up on your comments:

#p 2: (& pg 9) very good points, this narrows down the Flow Dash connect user story

#p 3: ok

#p 4a: If a user connects dash to flow using instance, api key & secret, why would they need to select an instance when dash detects access to flow if they only authenticated specifically to one?

#p 4b: we have been thinking to provide a survey's folder breadcrumb alongside the survey name in the dropbox. The drawback with the full scale folder structure navigation is reducing complexity - the number of ui elements and the need for these to be traversed [a suggestion for unique survey names rather than hierarchical folders for flow - a bit irrelevant here]

#p 4c: Regarding the flow data import, there had been 3 suggestion: a) import the registration form alone, b) import the registration form and some select forms (including selecting the specific questions) and c) import the whole survey. Personally, I think option (c) is the most robust, since it covers all others and as you mention - enables us to treat transformation after a dataset creation not before or after import. It would also enable us to avoid the "Joining" of some previously imported questions with some yet to be imported questions from the same survey. This issue I feel is still open for a decision..

**Comment by mtwestra** [comment]
@iperdomo, @kiarii,
We seem to agree that the process is:
1) detect if user is logged into FLOW
2) if not, ask user to login to FLOW, or provide Instance, key, secret

On the selecting a survey in FLOW: I think we can't escape from the folder structure. It is an essential part of keeping things organised, and people will expect it

On the import: I agree with Ivan that the system should load a whole survey, and than inside DASH the user can select forms, hide columns, etc.

**Comment by mtwestra** [comment]
@kiarii, Here are some examples of how a registration form and monitoring form can be joined:
[joins.xlsx](https://github.com/akvo/akvo-product-design/files/197321/joins.xlsx)

**Comment by mtwestra** [comment]
@kiarii, some examples for a repeated question group
[repeatedQuestionGroup.xlsx](https://github.com/akvo/akvo-product-design/files/197384/repeatedQuestionGroup.xlsx)

**Comment by Kiarii** [comment]
@mtwestra I see now the possible Join options; we need to define these (as user stories and use cases) in order to determine the easiest way to provide these options in a simple and meaningful way to the users. I think if we are importing whole survey data, we could leave these Joins to be the first Actions (transformations) that the user has to do before they can view & further edit the data - since after creating the dataset, we can use previews to show the user exactly what would happen to the data with the application of a specific Join-option. The dataset creation process then remain simple, and the Join action applied conceptually and visually a transform log item

**Comment by Kiarii** [comment]
@mtwestra, @iperdomo here is an update to the Akvoflow-source Dataset creation process mockups: https://drive.google.com/file/d/0B4C2-GDdmwzKajlWSW4tMlFsTlE/view?usp=sharing

**Comment by Kiarii** [comment]
Update:

https://drive.google.com/file/d/0B4C2-GDdmwzKRUhJWWt6RUwyalE/view?usp=sharing
 
[change: The list of connected instances includes both instances that the user has access to using their Dash account and those that they have connected to using the Instance API details]
