### ISSUE TITLE
Capturing location data improvements 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-product-design#259]
Currently when the user captures data for a location question we save and show this information: 
- latitude (capture and show)
- longitude (capture and show)
- height (capture and show)
- accuracy (only show)
- geocode (capture in raw data exports)

The need for latitude and longitude is clear. But questions arise around the other items as: 
- **Height** What is the use of variable? Is it needed to show on maps? Can we work with only lat and log? 
- **Accuracy** Considering we already show it on the app, would it be possible to save the value and show it with the data (in the data tabs and exports). Accuracy can give a lot of insight to the users and the precision of the captured location of the point 
- **Geocode** What is the use of this variable in the exports? Why do we have it there? Can we remove it? 

@muloem and @stellanl perhaps you both can bring some clarity to these questions? Thanks

**Comment by stellanl** [comment]
Height can be interesting when analysing things like crop yields, pollution, soil chemistry. And perhaps some health issues are altitude-related. Think Nepal... Maybe dwe can rop it from showing on vanilla maps, but we should keep it in the data.
Accuracy we could easily collect and handle just like height. 
The Geocode has been around since the start, I think, so WfP may have had a requirement for it. (It lets you roughly group things geographically even in a stupid database.) We could ask Chris or Dru.

**Comment by janagombitova** [comment]
Thanks @stellanl for the details. @muloem what are your thoughts? 

Stellan, based on your comment, I would then suggest we could consider removing Geocode from the data set and adding Accuracy instead. But with showing Accuracy not only in the exports, but also on the Data tabs and maps with the data. We would then need to consider how to deal with accuracy if the geolocation is input in manually, what should we show there.

**Comment by janagombitova** [comment]
Two issues created in Flow repo based on the discussion we had here: 
- Remove geocode: https://github.com/akvo/akvo-flow/issues/2367
- Add accuracy: https://github.com/akvo/akvo-flow/issues/1761
