### ISSUE TITLE
Sharing individual visualisations from public dashboards

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-product-design#270]
Created via Reamaze by Lynn:

As a visitor to a public dashboard, such as https://demo.akvolumen.org/s/tgdAOXjc8Ws <https://demo.akvolumen.org/s/tgdAOXjc8Ws> , I notice that the graph/visualisation G4AW VN - Fertilizer, exactly relates to research I am doing into how fertilisers affect the agricultural soil quality.
I need a share option on only that specific visualisation so that only the relevant visualisation can be shared to my social media followers on Twitter and Facebook or displayed on my own website within the content related to my research on the subject.
Of course if the dashboard is not public, this option should not be available to me, and if the dashboard is public the Lumen user should decide whether the option to ‘share’ is available.

A use case for this would be one of Lars Heemskerk’s West Africa Akvo Sites where data is currently visualised via a plugin, as well as the GT2.0 Swedish demo case where it would be useful for a visitor to the FreshWaterWatch Lumen integration page may want to share a visualisation.

**Comment by Kiarii** [comment]
Good suggestion, I think if the dashboard is public then anything within it should be shareable; if private, then nothing or via private (password) sharing.

@nadiagorchakova lets discuss this with Loic and Gabe to see how to proceed and into which milestone it goes. On the side of design it doesnt require much effort but it may be otherwise on the implementation end

**Comment by janagombitova** [comment]
Moved to Lumen's repository
