### ISSUE TITLE
Repeat question groups

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-product-design#35]
### Overview
The aim is to introduce repeated question groups. Often, a number of questions need to be asked multiple times, for example if you want to ask a number of questions to each member of a household. This functionality lets the user specify that a question group will be repeated a number of times.

The functionality will include:
* A way to mark a question group as 'repeated question group'
* A way to fix the number of repetitions by letting it depend on the answer to a number question: 'how many members does your household have?'
* If the user doesn't supply a repeat number, the enumerator will be prompted to add another set after he/she finishes the last question of the group.
* a way to let the number of repeats depend on an earlier option question
* a way to let the number of repeats depend on a static list of items.

* displaying the repeated questions in the RAW data reports

### Links to documents
https://github.com/akvo/akvo-product-design/blob/master/FLOW/Features/35-RepeatQuestionGroups/FunctionalDesign.md
https://github.com/akvo/akvo-product-design/blob/master/FLOW/Features/35-RepeatQuestionGroups/VisualDesign.md
https://github.com/akvo/akvo-product-design/blob/master/FLOW/Features/35-RepeatQuestionGroups/TechnicalDesign.md

### Links to issues
https://github.com/akvo/akvo-flow-mobile/issues/257
https://github.com/akvo/akvo-flow/issues/269

**Comment by mtwestra** [comment]
The first implementation will include a way to mark a question as a repeat question group. On the device, the enumerator can create new copies of the group.

**Comment by ichinaski** [comment]
Question not belonging to the same group cannot depend on a repeatable group's questions. Allowed dependencies:
  * [x] Repeatable question on an external group question
  * [x] Repeatable question on a repeatable question **within the same group**
  * [ ] External question (different group) on a repeatable question

**Comment by ichinaski** [comment]
To flag the presence of a multiple-value response (JSON encoded), the data.txt file will include a new column (14th) whereby we can determine such property. This *multiple* column can hold the values `true` and `false`.

**Comment by janagombitova** [comment]
*Downloading the collected data of repeated question groups as a RAW data report* 

There are two ways of dealing with downloading data: 
(1) a human friendly and readable view as an Excel file = Report 
The data can be represented either as a matrix, which is part of the sheet with all the other answers to all the questions in a form, or as a separate sheet that holds the referenced location, as in relation tables. For the current implementation we will use the matrix view (see attached picture).

The matrix view will hold a column, which indicates the order of repeats, followed by the questions from the groups. Every new repeat stands in its own row.

(2) a 'machine readable format' in JSON = Export. 
This would mean to re-write the full report into JSON format (no excel formatting at all).

![matrix representation](https://cloud.githubusercontent.com/assets/12456965/8308605/0c382502-19c6-11e5-9d4e-f79faaec49e3.png)

**Comment by janagombitova** [comment]
in the question picker for dependent questions, exclude questions in repeated question group

**Comment by ichinaski** [comment]
@loicsans could you perhaps look into the visuals for:
* Setting up the `repeatable` flag in a question group
![qg](https://cloud.githubusercontent.com/assets/1754343/8408836/3ea34e64-1e6b-11e5-8f5e-8c320ca4b509.png)
* Response visualization for the dashboard (see mockup)

**Comment by janagombitova** [comment]
Viewing the collected data in forms with repeatable question groups on the dashboard

We have decided for the 'list' view instead of the matrix view. The matrix view would make the list of questions and answers less comprehensive. Secondly, instead of showing the question ID we will replace it with the order of the questions. Thirdly, the groups names will be added to this view. 

![list view](https://cloud.githubusercontent.com/assets/12456965/8409108/72208c70-1e75-11e5-9f89-4379d072a033.png)

**Comment by Kiarii** [comment]
the response visualization for the dashboard illustrated by the wireframe sketch above seems quite logical

**Comment by Kiarii** [comment]
regarding the setting a group as repeatable; here are two options:
![repeat group flag](https://cloud.githubusercontent.com/assets/12692444/8569602/f190c32c-2581-11e5-8c19-88abdca1b673.png)

**Comment by muloem** [comment]
@Kiarii my first thoughts are that the flag option should only appear when the group is in edit mode, i.e. when editing data related to the group in this case the group name.  This also avoids accidentally selecting this option as a user will be intentionally know that they are in edit mode. With that in mind, moreover, perhaps its good for us to consider removing the links like `Edit Group Name` and also to make the rest of the icons `Move`, `Copy` and `Delete` more in line with what appears for the Folders and Surveys.

**Comment by Kiarii** [comment]
@muloem that is a very good observation. The eventual design should depend on how much of a redesign of the group we are looking to do; If we do an overhaul as you suggest, then the Group name and the repeatable setting just need to be visually grouped so that the are visibly separated from questions. I had the feeling that atm we are just adding the repeatable group setting without changing much else, correct me if I am wrong

**Comment by muloem** [comment]
Perhaps @janagombitova can also weigh in here but if the overhaul is not going to take a lot more time, it may be worth it in this particular case.

**Comment by muloem** [comment]
Also it would help to make the whole group interface more coherent. I have the feeling that smacking in a new setting without adapting some of the current design will give us a bit of a strange end result.

**Comment by janagombitova** [comment]
@Kiarii and @muloem I agree that we need to redesign the entire survey creation part and especially unify the actions (what happens when I click on something, where icons are located, etc.) This is planned for January, so for now I think we need a solution, which will make it clear what the checkbox means, is not the first setting the user can work with, but is not too hidden at the same time. 

My suggestion for now is based on Kiarii's second design:

A: New question group

1. User clicks on 'insert group here'
2. User clicks on 'edit group name' and saves the new name
3. User clicks on 'show questions'
4. NOW user sees under the group name the option to select if a group is repeated or not
  - I would use "Repeat this group."
  - Selection happens via a check box as proposed
  - Next to the checkbox + "Repeat this group" is a help button ('?'), which explains in more detail what does it result in if the user makes a group repeatable. 

B: Existing question group
Same procedure, so the user sees the option the make a group repeatable or not after opening the group up to see the questions.

**Comment by Kiarii** [comment]
I agree with @janagombitova; given that we are not looking to make big changes I think we could use the second option; that way the functionality is not hidden so much.

**Comment by Kiarii** [comment]
The 3rd sketch illustrates the added suggestion:
![repeat group flag](https://cloud.githubusercontent.com/assets/12692444/8571384/17f20226-258f-11e5-9568-130f19c8dc5d.png)

**Comment by janagombitova** [comment]
Here is the text for the "?" button:

Often a number of questions need to be asked multiple times, e.g. when you want to ask the same questions to each member of a household. This function lets you specify that a question group is repeated a number of times during the collection of the data.

**Comment by janagombitova** [comment]
We need to also add a help text/information for the user on the limitation of the dependency rule (within the repeated question group and outside these question groups)

Suggestions: 
1. add a general "?" button next to the Dependent checkbox which will explain the limitations and will be visible for all questions
2. add a line of text under the Dependent checkbox explaining the limitations 
3. On the Group level explaining the limitations regarding Dependency

**Comment by Kiarii** [comment]
An option for the in-app Repeat Group trigger:

We could consider "Add a Repeat", "New Repeat", or sth along these lines..
![repeat group trigger alt 5](https://cloud.githubusercontent.com/assets/12692444/8935173/029bcc84-3554-11e5-86df-caaf9cfe03b2.png)

**Comment by janagombitova** [comment]
Suggestions for naming the button:

1. Repeat questions
2. Add new set
3. Repeat set 
4. Add a repeat
5. Repeat this group

After talking with Mark, Communication team and the partner team, we chose: **"Repeat this group"** (it is consistent which the setting on the dashboard as well)

**Comment by loicsans** [comment]
![screen shot 2015-08-05 at 08 31 02](https://cloud.githubusercontent.com/assets/1717219/9078905/d2d135bc-3b4c-11e5-8fdc-c3aa6b6db942.png)

**Comment by janagombitova** [comment]
@loicsans @Kiarii Beautiful!

**Comment by muloem** [comment]
@janagombitova the column containing the repeat iteration number has the header "Repeated #" correct?  @iperdomo @ichinaski what would be an appropriate Spanish translation for this?

@jonase @iperdomo this is connected to https://github.com/akvo/akvo-flow/commit/b3a3549c03314f358330bc57b0513ae8df2adc59#diff-f619b9ce27038df4b9ade2d5ccedd531R227

**Comment by janagombitova** [comment]
@muloem Yes that is how it is in the mock ups. We did not talk about the vocabulary, but I think it can stay like that.

**Comment by janagombitova** [comment]
First implementation deployed in 1.9.1 FLOW. Following implementation: https://github.com/akvo/akvo-product-design/issues/113
