### ISSUE TITLE
Computed-value question type

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-product-design#37]
### Overview

In many cases, users want to compute a value based on a single answer or multiple answer. This can be used for example to implement a simple decision tree: 'if respondent has income < 10.000, and she has 5 children in her household, then respondent qualifies for support'. Another use case is to implement scoring: for example giving a score from 1 - 10 for the sustainability of a water pump, based on the answers to multiple questions about the situation.

In many cases, it is useful to compute this value right on the device, so it can be used to display certain questions, and to save it as part of the responses.

This functionality will include:
- users can create a 'computed value' question
- users can use a formula builder to describe the calculated value
- the calculated value is hidden from the user (to show it, see issue #38), but it is available for validation and display logic
- the calculated value becomes part of the saved responses and is send to the server in the usual way

**Comment by janagombitova** [comment]
DRAFT 

Scoring using cascade: http://flowsupport.akvo.org/article/show/25053-using-predefined-scores
Benefits: - re-usable in more forms 
Scoring cases now using cascades: https://marsfood.akvoflow.org/admin/ > Cambodia > Mars + Sustainable Rice Platform Cambodia > 3. Sustainable Rice Platform 

# Context 
## Who
## What 
## Why
# Problem or opportunity 
# Next steps

**Comment by janagombitova** [comment]
We have learned that scoring can have two use cases that are very relevant to how we implement it: 
- is the score supposed to be directly visible to the respondent? 
- is the score needed for analysis of the data? 

If the first then this should be considered a survey editor change, if second then it is a Lumen issue. We have heard more use cases for the second case, thus for now we shall handle it in Lumen's repo and close this issue here for now. If we receive requests for the first case we can open an issue in Flow's repo for the form editor
