### ISSUE TITLE
Offline maps

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-product-design#68]
The aim of this feature is to enable the FLOW app to download offline maps. The use case is that in the field, having access to maps is data-intensive operation, and therefore should be cached offline.

Preliminary features are:
1) App uses a map sdk that allows offline maps, both satellite and street tiles
2) Enable the user to specify a region on a map for offline download
3) Enable the app to check if enough space is available for caching
3) Enable the app to download and cache tiles for the specified region, similar to the google offline map UI
3) Enable the user to choose between satellite and street map.

**Comment by ichinaski** [comment]
From https://github.com/akvo/akvo-flow-mobile/issues/238#issuecomment-68522105

# OSMdroid

[OSMdroid](https://github.com/osmdroid/osmdroid) is a (almost) full/free replacement for Android's MapView (v1 API) class. It also includes a modular tile provider system with support for numerous online and offline tile sources and overlay support with built-in overlays for plotting icons, tracking location, and drawing shapes.

A nice addition to this core library would be [osmbonuspack](https://code.google.com/p/osmbonuspack/), which includes some goodies like marker clustering.

# Mapbox

The [Mapbox Android SDK](https://github.com/mapbox/mapbox-android-sdk) is basically an osmdroid fork, with some significant differences:

* GeoJSON and TileJSON support added.
* The Mapbox Android SDK is Apache 2.0 licensed, and does not include any GPL or copyleft add-ons.
* Mapbox Android SDK is a small core design. OSMDroid's semi-related utilities like GPX uploading, UI zoom buttons, GEM & Zip file support, Scale Bar, Compass Overlay, and more have been removed. These requirements will be better served by separate modules that do one thing well.
* Interfaces and abstract classes are only defined when suitable: most single-use interfaces are removed for simplicity.
* Data objects like points and lines use doubles instead of the E6 int convention. This simplifies implementations. The reuse pattern is also deemphasized, since it's less necessary with newer JITs.
* Instead of supporting specific tile layers with hardcoded paths, Mapbox Android SDK provides an easy-to-configure TileLayer class.
* Small modules are used in place of local implementations - DiskLRUCache for caching, OkHttp for connection niceties, and android-geojson for GeoJSON parsing.
* Markers can optionally use the Mapbox marker API for customized images.
* Code style follows the Sun conventions
* Automated tests are included.
* slf4j dependency is removed

Still, Mapbox for Android (unlike the iOS counterpart) does **not** have clustering support. There seems to be some ongoing discussions around this topic (https://github.com/mapbox/mapbox-android-sdk/issues/538), but the clustering integration is not implemented yet. It looks like the project did have some clustering integration in the past, but due to some (performance?) issues, it was fully removed (https://github.com/mapbox/mapbox-android-sdk/issues/303)

## Other alternatives to consider

* https://github.com/microg/android_external_osmdroid (osmdroid fork)
* https://github.com/mapsforge/mapsforge

**Comment by ichinaski** [comment]
After an in-depth research on the aforementioned possibilities and a chat with @mtwestra, we have reached the conclusion that none of the existing approaches is ready to fulfill our requirements.

**Mapbox** for Android is under a lot of development, and a myriad of progress can be seen in the community. However, the capabilities of its SDK fall way behind the iOS counterpart, which already supports vector tiles. Since this is not implemented (yet) in the Android version, only image tiles can be displayed, which works fine for on-the-fly fetched maps (online), but gets ridiculously inefficient when it comes to download a whole region.

For now, we are going to check out the status of https://github.com/mapbox/mapbox-gl-native/tree/android-mason, which looks like the ongoing effort of porting the mapbox-gl-native component to Android. However, we will probably just wait until this, or any other vector-based solution, is officially released, before attempting to integrate offline maps features into FLOW.

**Comment by mtwestra** [comment]
We'll wait until Mapbox has made progress on this.

**Comment by janagombitova** [comment]
https://www.mapbox.com/android-docs/map-sdk/overview/offline/

**Comment by janagombitova** [comment]
Closing this issue as we are handling it directly in the Flow mobile repo here: https://github.com/akvo/akvo-flow-mobile/issues/238
