### ISSUE TITLE
Enable webforms

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-product-design#70]
The aim is to introduce web forms, in which people can fill FLOW surveys in an online web form.

Documents:
- Functional Design: https://github.com/akvo/akvo-product-design/edit/master/FLOW/Features/70-WebForms/FunctionalDesign.md
- Technical design: https://github.com/akvo/akvo-product-design/edit/master/FLOW/Features/70-WebForms/TechnicalDesign.md
- Visual Design: https://github.com/akvo/akvo-product-design/edit/master/FLOW/Features/70-WebForms/VisualDesign.md

**Comment by mtwestra** [comment]
Decision:
* Flow services reads XML
* Flow services exposes API with form definition (JSON)
* Client reads JSON and creates html form
* Client delivers JSON answer to flow services
* FLOW services stores answers

**Comment by mtwestra** [comment]
Need to break this down into smaller chunks

**Comment by mtwestra** [comment]
After considering the use cases for SNV, and discussions with @janagombitova and @muloem, we propose the following changed approach to this:

Actual use case:
* logged-in users can create new data points by filling in the registration form
* logged-in users can add a monitoring form to an existing data point

From the requirement of a logged-in user, and the requirement to show existing data points, this use case is quite different from the one initially envisaged. Therefore, we propose the following implementation:

* Instead of creating a separate app that handles the webforms, handle the web forms inside the dashboard. This saves a lot of work in terms of building a new app, authorization, etc.
* Inside the dashboard, underneath the data tab, combine the monitoring tab with the inspect data tab, following the existing design created by @Kiarii (Jana will add it in a comment to this issue). This change was already foreseen in the large restructure we want to do next year, and is based on the work we did for issue #100.
* Inside the new tab, add a button 'create new datapoint'. When clicked, this shows a webform which can be filled and submitted.
* The webform can also be used also for showing a preview of a survey, and when editing an existing data point form.

This approach has the additional benefit of requiring far less additional infrastructure work.

Details:
* when a data point is filled in on the dashboard, for the device id, we will use the format "webform - IP_ADDRESS". For the submitter, we simply use the user name. The other properties in the report will be the same.
* Repeat question groups will work in the same way as in the app.

Roles:
We probably need to add a role "Submit webform", to define who sees the 'add datapoint' button.

Structure:
A question is if we want to show the form as a single page with all the question groups beneath each other, or if we want to show tabs. If we don't want to use local storage, this might be an argument for using a single page view.

Limitations:
All question types will be supported, with the exception of a geoshape.

Technical implementation:
We could try to implement this as a react component, so it can be reused in the new refactored dashboard.

@iperdomo, @kiarri, @loicsans, @muloem any comments?

**Comment by loicsans** [comment]
When is it due to be released?

**Comment by iperdomo** [comment]
> for the device id, we will use the format "webform - IP_ADDRESS

i think that "Webform" is enough as `Device ID`. The IP address can't reliable identify a device (e.g. multiple users behind a proxy).

**Comment by mtwestra** [comment]
This year, as part of the SNV deliverables. That is why the simplification is most welcome

**Comment by mtwestra** [comment]
@ivan, good point.

**Comment by janagombitova** [comment]
@Kiarii and @Loic I copied the mockups from the work we have done in the summer on viewing monitored data into this one. I think it is a good starting point from which we can pick up the work and add the extra webforms' related functionality. 

https://drive.google.com/drive/folders/0B53AXQ5Y0VCMN1NJbjVqVGVoNWc

**Comment by joycarpediem** [comment]
Does this mean that the user who only has access to "Submit Webform" can see only that tab when he logs into the dashboard ? 
If not then the  new approach does provide implementation simplification, it also means that we are combining data collection and data management which will not suit most of our partner needs.

**Comment by mtwestra** [comment]
@joycarpediem we will need to define that further. The idea is to make 'submit webform' as a separate permission, so if you only have that permission, you only can do that.

Do you happen to have a list of the partners that want to use this functionality, and how they would like to use it?

**Comment by jonase** [comment]
I suppose we also need to make sure that we use a **published survey** as basis for rendering and submitting the webform and not rely on what happens to be in the datastore?

**Comment by janagombitova** [comment]
After the call with @muloem, @loicsans and @Kiarii we have agreed that considering the implementation timeline we have currently, the approach of filling in the webforms within the Dashboard, migrating the  Inspect data tab and the Monitoring tab and adding a "submit webform/create new data" button there is an OK approach for the time being. Further clean up and design improvements will be needed later. 

A new permission will be created, based on the current permissions structure we have (create, view, edit, delete): Create data

**Comment by joycarpediem** [comment]
From partners perspective the added advantage of webforms are
1. They can utilise existing infrastructure for data collection without the need for a dedicated data collector. Prime examples will be Schools, Health centres and and such public institution projects which already has basic infrastructure in place. These entities generally report data on a regular basis

2. Partners who have already invested in non-android data collection infrastructure can collect data with webforms

So ideally with forms should "mimic" the android app in a browser with reasonable constraints.
This also means that the webforms user should not have visibility into the questionnaire designer , device management etc or have the ability to lookup or download data. Partners may not be comfortable with this because they would mean that they are opening up their data to a much bigger audience than they intended to which may have undesirable ramifications. 

An implementation of webforms where it is totally detached from the survey creation and data management part of the workflow will be a lot easier and comfortable for partners to roll out .

With how roles and permissions is designed right now, the dashboard still does not mimic that isolated environment that partners would want data collection to happen .

**Comment by iperdomo** [comment]
Agree with @joycarpediem the idea of having a _detached_ component that is web based and able to submit response for a particular form, is way more usable (imho) then having _webforms_ within the current Dashboard. The current approach seems a _quick fix_, that later we'll need to re-implement.

cc/ @janagombitova @mtwestra @muloem @jonase

**Comment by muloem** [comment]
Just for clarification. The webforms will be implemented as a component that can be used in isolation i.e detached from the dashboard or embedded within the dashboard.

**Comment by loicsans** [comment]
@iperdomo what @muloem says was my understanding too. If we need to rethink the whole thing in a few months, then we should hold on doing any work on this until we refactor the whole dashboard.

**Comment by iperdomo** [comment]
@muloem do we have a technical explanation on how decoupled will be from the Dashboard? I've not being involved in the technical conversation.

**Comment by muloem** [comment]
@iperdomo Webforms will be a implemented as a js client as discussed originally and for this use case we will embed it in the dashboard but it will also be possible to use it in a standalone application. So actually the original idea stays but this scenario (embedding into the dashboard) can also be supported.

**Comment by janagombitova** [comment]
I agree with you @joycarpediem. That is another use case for webforms. We basically have two different broad user stories on how to use webforms:
1. the one you talk about - having a 'outside' environment where the submitter simply opens the webform and submits the data, without being involved in any further way in FLOW (used for crowd-sourced data collection)
2. one where the partner wants to have more information: on who submits the data, and also gives insight for the submitter in the case of monitoring (adding data to existing data points) 

As @muloem and @loicsans pointed out, the current suggestion is a quick solution focusing mostly on the second case. Later, we will need to put more UX thought into the webforms and build and design them in such a way that suits both user stories. 

For now, I think we can limit the users access by fixing up the existing roles and permissions and making sure, that if I only have the right to 'create new data = submit a webform' I cannot edit surveys, I cannot edit data or delete anything, and can view only the survey that was assigned to me. 

Lets look at this as a quick implementation of a MVP for webforms while keeping in mind that further improvements will be coming.

**Comment by janagombitova** [comment]
### Webform survey rendering

https://github.com/akvo/akvo-flow/issues/1347

@muloem here is the mockup for form preview. @Kiarii approved it a few weeks ago. There are some questions that need to be clarified, as if we will show both survey name and form name, as this depends if the webform is filled in within the dashboard or as a separate full screen pop-up, should some defaults texts be added or not, etc? But we can tackle those later in the implementation. 

![webform survey rendering](https://cloud.githubusercontent.com/assets/12456965/11650526/23f83ffe-9d8a-11e5-8b77-1e0bdee4ece7.png)

**Comment by janagombitova** [comment]
@muloem Here are the mock ups made by Kiarii, there are still some details we need to work out, but the workflow is final. 

**For a monitored survey**
https://drive.google.com/open?id=0B53AXQ5Y0VCManJNYndnWVdCWlk

**For a non-monitored survey**
https://drive.google.com/open?id=0B53AXQ5Y0VCMOThfUnV3elppak0

**Comment by janagombitova** [comment]
* [ ] add 'create data' permission to the current list- will make the webform submission buttons visible in the Data tab

**Comment by janagombitova** [comment]
With this feature we are aiming to fit 2 different use cases: 
1. crowdsourcing of data collection - the dashboard user can generate a link for a form and share it with anyone to fill in in a separate tab from their desktop.
2. controlled data collection using a desktop - filling in data via a webform while being logged into the FLOW dashboard in order to know who submitted the data (a 2nd way to collect data using FLOW)

After looking at the implementation plan, feature description, mockups, last open questions and current timeline we have, @mtwestra, @muloem and myself decided to change the plan to the following. 
- we will continue with implementing the 2nd use case first. The ability to use generate an external link will be implemented in the following iteration
- we will **not** merge the Inspect data tab and Monitoring tab as originally planned in the above shared mockups 
- thus users will be able to submit a webform only via the Inspect data tab
- it will be possible to only submit a registration form in this 1st iteration
   - in the Inspect data tab when previewing submissions for a monitored survey there is currently no simple way of seeing which submission belongs to which data point 
   - in order to submit a monitoring form, it is better to first improve the way the users view data points (as proposed in Kiarii's mockups) to make the data point selection and following form selection more simple 
   - in the dropdown folder > survey > form selection if the user selects a monitoring form, the 'New datapoint' button that brings the user to the webform should not be visible, or should be disabled 
- we need to create a permission which will enable a user to submit a webform for a particular survey

This change of plan will make it more possible for us to implement this 1st steps of this feature in the given timeframe, it breaks down the "big plan" into even smaller steps, and makes it possible to still deliver the desired (and expected) functionality. 

**To be answered:**
- Does the user need to have the 'View data' permission in order to have the permission to submit a webform? 
- Does submitting a webform (monitored survey - registration form) automatically generate the data point which can be synced into the app?

**Comment by janagombitova** [comment]
### Implementation plan 
This is a summary of all the decisions mentioned above, implementation steps, relevant documents and mockups. We will implement webforms in multiple small steps in order to slowly deliver parts of the functionality (contractual deadlines) while keeping adding the following steps. 

The steps are: 
   1. submit a webform in the Inspect data tab only for registration forms (no changes to how data is being viewed in the Data tab)
      - mockups 
      - Functional design document   
   2. submit webforms for monitoring forms 
      - involves changing how data is being viewed in the Data tab to give a more simpler and clean way to view data points and their forms. Thus with this step we will also merge the Inspect data tab with the Monitoring tab 
      - mockups (currently being finalised)
         - [For a monitored survey](https://drive.google.com/open?id=0B53AXQ5Y0VCManJNYndnWVdCWlk)
         - [For a non-monitored survey](https://drive.google.com/open?id=0B53AXQ5Y0VCMOThfUnV3elppak0)
      - [Functional design document](https://github.com/akvo/akvo-product-design/blob/master/FLOW/Features/70-WebForms/Feature%20definition%20-%201st%20implementation.md) (work in progress) 
   3. generate external link to submit webforms for registration forms outside the Akvo FLOW dashboard
   4. explore the need to generate external link to submit webforms for monitoring forms outside the Akvo FLOW dashboard

**Comment by janagombitova** [comment]
accidentally closed this issue - please ignore it

**Comment by janagombitova** [comment]
### Implementation plan 
This is a summary of all the decisions mentioned above, implementation steps, relevant documents and mockups. We will implement webforms in multiple small steps in order to slowly deliver parts of the functionality (contractual deadlines) while keeping adding the following steps. 

The steps are: 
   1. submit a webform in the Inspect data tab only for registration forms (no changes to how data is being viewed in the Data tab)
      - mockups 
      - Functional design document   
   2. submit webforms for monitoring forms 
      - involves changing how data is being viewed in the Data tab to give a more simpler and clean way to view data points and their forms. Thus with this step we will also merge the Inspect data tab with the Monitoring tab 
      - mockups (currently being finalised)
         - [For a monitored survey](https://drive.google.com/open?id=0B53AXQ5Y0VCManJNYndnWVdCWlk)
         - [For a non-monitored survey](https://drive.google.com/open?id=0B53AXQ5Y0VCMOThfUnV3elppak0)
      - [Functional design document](https://github.com/akvo/akvo-product-design/blob/master/FLOW/Features/70-WebForms/Feature%20definition%20-%201st%20implementation.md) (work in progress) 
   3. generate external link to submit webforms for registration forms outside the Akvo FLOW dashboard
   4. explore the need to generate external link to submit webforms for monitoring forms outside the Akvo FLOW dashboard

**Comment by janagombitova** [comment]
Closing this issue in both repositories for now as we have stopped the implementation a few years ago and a lot has changes since around the product strategy. We decided to focus on in field data collection where mobile collection is more of value. We can reopen it if relevant and of value.
