### ISSUE TITLE
Pricing structure system needs

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-product-design#72]
### Overview

The aim is to introduce changes to the system that can help implement the new FLOW pricing structure.

This will mean we need to tackle questions:
1) How to calculate the number of devices and forms?
2) How to determine what will not be added into the count? (Akvo devices, trainings, devices used only a few times, etc)
3) How to inform the users of their status, usage, etc.

Initially we will create a script to calculate the number of user devices and forms and manually determine the pricing plans for partners, as well as their current usage statues. In the second phase we will create a Unified log consumer to read this information automatically and a UI, which will provide the user with information directly. The second phase will happen once the Unified log is running on all instances. 

### Steps to take:
1. create script
2. add Android ID to the collected data - https://github.com/akvo/akvo-flow/issues/998

### Links to documents

https://github.com/akvo/akvo-product-design/blob/master/FLOW/Features/72-PricingStructureNeeds/FunctionalDesing.md

**Comment by kendragmterry** [comment]
Does this mean we will have a pricing tear for smaller, more grassroots types of organization?

**Comment by bjelkeman** [comment]
Yes, Kendra. See http://akvo.org/blog/pricing-akvo-flow/

**Comment by muloem** [comment]
@janagombitova @mtwestra 

1. What format are we looking at exporting the final results?
2. How do we intend to communicate this to partners, automatically or manually drafted email from somebody?
3. We still have the difficulty of how to identify which are Akvo devices

**Comment by janagombitova** [comment]
Here is my point of view on what we should do for now: 

Question 1: A spread sheet for now? For us to see and manually count the numbers of used devices and forms in order to keep the partners informed and for billing purposes.

Question 2: At this stage I think we will communicate manually. Later on we want to add a user interface which will show the count of devices and forms, which pricing plan the user is on, etc to the dashboard, where the user will automatically see all the information. 

Question 3: I have two ideas on how to tackle it: as you suggested change all akvo devices names to start with 'akvo - name' and then filter the number out, or we decide on an estimated set amount of devices (based on experience, we can estimate that usually for each instance XY akvo devices are used), which we will deduct from the count of devices.   

Let's talk on these questions.

**Comment by janagombitova** [comment]
Flow pricing has moved to be only determined by the number of forms submitted. Secondly, we have chosen to tackle this issue together with other Akvo tools using story mapping. Archiving this issue and saving the notes for further reference.
