### ISSUE TITLE
IATI partner types

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-product-design#84]

**Comment by mtwestra** [comment]
We need to replace Akvo partner types by IATI partner types. 
There are a number of question on how to proceed here. 

The definitions:
Links: http://iatistandard.org/201/activity-standard/iati-activities/iati-activity/reporting-org/
http://iatistandard.org/201/codelists/OrganisationRole/

supporting partner = reporting org

RSR   =   IATI
funding partner => funding org
field partner => implementing org
Reporting organisation = ?
Secondary reporting organisation = Akvo?
support partner => Accountable org, Extending org?
extending = ?

For sponsor organisation: on project page, where currently the sponsor org is displayed, we need to display some other indication of participation

**Comment by lauraroverts** [comment]
IATI talks about Reporting organisation ánd Participating organisations (funding, implementing, accountable, extending organisations)

**Comment by lauraroverts** [comment]
Context
With RSR 3.0 there is confusion about the different partner types. We need to look into this and make it clear if we look at the partner types from a partner perspective or from an Akvo perspective. 

In addition: we used to work with sponsor partners. This ‘partner’ was created in order to make Akvo Pages for campaigns (e.g. Walking for Water) and consortia (e.g. Connect4Change). Now we can make Akvo Pages by adding keywords to a project. 

We need to replace Akvo partner types by IATI partner types. IATI talks about Reporting organisation ánd Participating organisations (funding, implementing, accountable, extending organisations)

Reporting organisation = The organisation issuing the report. May be a primary source (reporting on its own activity as donor, implementing agency, etc) or a secondary source (reporting on the activities of another organisation). This is not clear to me. It thus can be any organisation?

Participating organisations = 
- Funding org = The government or organisation which provides funds to the activity (same as Akvo’s funding partner)
- Implementing org = The organisation that physically carries out the activity or intervention (same as Akvo’s field partner)
- Accountable org = An organisation responsible for oversight of the activity and its outcomes (= Akvo’s support partner?)
- Extending org = An organisation that manages the budget and direction of an activity on behalf of the funding organisation This is not clear to me. It thus can be any organisation? 

Requirements: 
- One organisations can have multiple partner types within the same or other projects. 
- A project can have multiple funding/implementing/accountable/reporting organisations.
- A project can have only one extending organisation.

Outstanding questions: 
- By removing sponsort partner, we need to add tag to project page to show part of larger consortium/campaign (#94)
- How are we going to change this for all current projects? We cannot simply replace Akvo’s partner types by the IATI partner types, since they don’t exactly match
- Where do we add the definition of partner types? Needs to be clear at a project page and in the admin.

**Comment by KasperBrandt** [comment]
Additional outstanding questions:

- How do we deal with partners using our API (e.g. Akvo Sites, Cordaid, VEI)?
  - They all use something like "partner type = field" to retrieve all field partners. If we were to delete or even rename field partners, these sites won't be able to retrieve field partners anymore.

**Comment by lauraroverts** [comment]
Done
