### ISSUE TITLE
Ability to create results framework in admin

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-product-design#90]
Requirements to be discussed

**Comment by mtwestra** [comment]
@lauraroverts, I've preliminary discussed this with @JosjeS and @mato74. We have focussed our discussion on how a user would define the results framework. Some items we discussed:
* A results framework is defined as a set of results, each with one or more indicators. The indicator types are output, outcome, and impact.
* The results framework is entered as part of a project definition, as part of the new admin interface
* The user defining the results framework should have access to the results framework of the parent project.
* The user can select a result, and one or more of the contained indicators
* When the user has selected a result, it is 'important' into the project being edited. Here, it forms a copy. The text of a copied indicator can not be edited, in order to maintain the integrity and aggregation of the data.

We made a first attempt at a workflow, which is shown below:
![resultsframework](https://cloud.githubusercontent.com/assets/478954/9813037/6ff67c1a-5882-11e5-9fa9-c0c436967258.png)

We need to discuss this with @loic and @Kiarii.
